project_id = "jfdgcwjadowaorvczicg"
project_url = "https://qylraoxgfeanaouhlacd.supabase.co"
project_anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5bHJhb3hnZmVhbmFvdWhsYWNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNTI2OTIsImV4cCI6MjA4MzYyODY5Mn0.S8YAYTzfyxi6I8a6Ro4o-6D0xrIrQMHYAiG2Ty6qrkE"
